flash:
  express:
    mch-id: BA0097
    secret-key: cde04a4490b14447f4b2f4966ba5d77a8d3fc7470243511aa00c75a269c55890
    warehouse-no: YOUR_WAREHOUSE_NO  # from getAllWarehouses API
    base-url: https://open-api-tra.flashexpress.ph  # sandbox
    # base-url: https://open-api.flashexpress.ph    # production

    # Your store/warehouse pickup address (shipper src address for rate estimation)
    src-province-name: Metro Manila
    src-city-name: Taguig City
    src-postal-code: 1634