spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/wisecart_dev?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:wisecart}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        type:
          preferred_boolean_jdbc_type: BIT

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  admin:
    email: ${ADMIN_EMAIL:admin@wisecart.com}
    password: ${ADMIN_PASSWORD:admin123}
  contact:
    recipient-email: ${CONTACT_RECIPIENT_EMAIL:sales@wisecart.ph}
    password: ${ADMIN_PASSWORD:admin123}
    firstName: ${ADMIN_FIRST_NAME:Admin}
    lastName: ${ADMIN_LAST_NAME:User}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
    refresh-expiration: 604800000
  file:
    upload-dir: ${UPLOAD_DIR:./uploads-dev}
    max-image-size: 5242880
    max-document-size: 10485760

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

flash:
  express:
    mch-id: ${FLASH_EXPRESS_MCH_ID}
    secret-key: ${FLASH_EXPRESS_SECRET_KEY}
    warehouse-no: ${FLASH_EXPRESS_WAREHOUSE_NO:}
    base-url: ${FLASH_EXPRESS_BASE_URL:https://open-api-tra.flashexpress.ph}
    src-province-name: ${FLASH_EXPRESS_SRC_PROVINCE:Metro Manila}
    src-city-name: ${FLASH_EXPRESS_SRC_CITY:Muntinlupa City}
    src-postal-code: ${FLASH_EXPRESS_SRC_POSTAL:1780}
    src-detail-address: ${FLASH_EXPRESS_SRC_DETAIL_ADDRESS:Unit 81E, Udings Compound St. Bernadette College of Alabang East Service Road, Cupang Muntinlupa City}
    src-name: ${FLASH_EXPRESS_SRC_NAME:WiseCart}
    src-phone: ${FLASH_EXPRESS_SRC_PHONE:09636026511}

maya:
  public-key: ${MAYA_PUBLIC_KEY}
  secret-key: ${MAYA_SECRET_KEY}
  base-url: ${MAYA_BASE_URL:https://pg-sandbox.paymaya.com}
  success-url: ${MAYA_SUCCESS_URL:http://localhost:3000/payment/success}
  failure-url: ${MAYA_FAILURE_URL:http://localhost:3000/payment/failed}
  cancel-url: ${MAYA_CANCEL_URL:http://localhost:3000/payment/cancelled}
  webhook-url: ${MAYA_WEBHOOK_URL:https://unrevertible-senaida-continentally.ngrok-free.dev/api/webhooks/maya}
 
logging:
  file:
    name: logs/spring.log
  level:
    root: INFO
    com.wisecartecommerce: DEBUG
