CREATE TABLE pending_checkouts (
    id BIGINT NOT NULL AUTO_INCREMENT,
    checkout_ref VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    payment_method VARCHAR(255) NOT NULL,
    shipping_address_id BIGINT,
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    postal_code VARCHAR(255),
    country VARCHAR(255),
    phone VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    shipping_fee DECIMAL(19,2),
    express_category INT,
    coupon_code VARCHAR(255),
    notes TEXT,
    order_id BIGINT,
    amount DECIMAL(19,2) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    maya_checkout_url TEXT,
    created_at DATETIME(6),
    expires_at DATETIME(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_pending_checkout_user FOREIGN KEY (user_id) REFERENCES users(id)
);